services:
  traefik:
    image: traefik:v3.2
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "redis_network"

  websocket-server:
    build: .
    ports:
      - "80"
    volumes:
      - ".:/usr/src/server"
    environment:
      SERVER_PORT: 80
      REDIS_URL: "redis:6379"
    networks:
      - "redis_network"
    deploy:
      mode: replicated
      replicas: 2
    ulimits:
      core:
        hard: 0
        soft: 0
    labels:
      - "traefik.http.routers.websocket.rule=Host(`localhost`)"
      - "traefik.http.services.websocket.loadbalancer.server.port=80"

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - "redis_network"

networks:
  redis_network:
    driver: bridge
