services:
  websocket-server:
    build: .
    ports:
      - "80-81:80"
    volumes:
      - ".:/usr/src/server"
    environment:
      SERVER_PORT: 80
      REDIS_URL: "redis:6379"
    networks:
      - redis_network
    deploy:
      mode: replicated
      replicas: 2
    ulimits:
      core:
        hard: 0
        soft: 0

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge
