# local development
services:
  websocket-server:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/usr/src/server
    environment:
      SERVER_PORT: 80
      REDIS_URL: "redis:6379"
    networks:
      - redis-network

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
