services:
  traefik:
    image: traefik:v3.2
    command: 
      - --api.insecure=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --log.level=INFO
      - --providers.swarm
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.network=traefik-public
      - --log.filepath=/var/log/traefik.log
    ports:
      - target: 80
        published: 80
        mode: host

      - target: 8080
        published: 8080
        mode: host

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik-public

  websocket-server:
    image: 10.0.0.178:5000/swarmtest
    environment:
      SERVER_PORT: 80
      REDIS_URL: "redis:6379"
    networks:
      - traefik-public
      - redis-network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.http.routers.websocket-server.rule=PathPrefix(`/app`)
        - traefik.http.routers.websocket-server.entrypoints=web
        - traefik.http.services.websocket-server.loadbalancer.server.port=80

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redis-network
    deploy:
      placement:
        constraints:
          - node.role == worker

networks:
  traefik-public:
    external: true
  redis-network:
    driver: overlay
